name: flutter_calendar_app
description: "A new Flutter project for a calendar application."

publish_to: 'none'

version: 3.0.0+3

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  intl: ^0.20.2
  lottie: ^2.7.0 # Add lottie package
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: false
  # 従来のAndroid、iOS用の画像 (通常は前景と背景を合わせた512x512のPNG)
  image_path: "assets/icon/foreground.png"

  # アダプティブアイコン設定
  adaptive_icon_foreground: "assets/icon/foreground.png"
  adaptive_icon_background: "#FFFFFF" # または背景画像のパス "assets/icon/background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.5.1

